services:
  app:
    build: .
    container_name: transflow_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
      - rabbitmq

  mongo:
    image: mongo:6
    container_name: transflow_mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: transflow_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: transflow_rabbit
    ports:
      - "5672:5672"
      - "15672:15672" 
      
  consumer:
    build: .
    container_name: transflow_consumer
    env_file: .env
    command: ["python", "-m", "faststream", "run", "src.consumer:app"]
    depends_on:
      - rabbitmq
      - mongo
      - redis
    restart: unless-stopped
